drop table if exists cat CASCADE;
drop table if exists owner CASCADE ;
create table cat (id bigint generated by default as identity, age integer, name varchar(255), owner_id bigint, primary key (id));
create table owner (id bigint generated by default as identity, dob varchar(255), name varchar(255) not null, primary key (id));
alter table cat add constraint FKlet4cncad4b281dourgr2687d foreign key (owner_id) references owner on delete cascade;